name = "MortalityTables"
uuid = "4780e19d-04b9-53dc-86c2-9e9aa59b5a12"
authors = ["Alec Loudenback <alecloudenback@gmail.com>"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[compat]
DataStructures = "0.17"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
