name = "MortalityTables"
uuid = "4780e19d-04b9-53dc-86c2-9e9aa59b5a12"
authors = ["Alec Loudenback <alecloudenback@gmail.com>"]
version = "0.8.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"

[compat]
DataStructures = "^0.16, 0.17"
HTTP = "^0.8"
XMLDict = "0.4"
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
